name: paginated
description: A simple, unopinionated Flutter package that adds pagination to your existing scrollable widgets like ListView, GridView, SliverList, and SliverGrid.
version: 1.0.0
homepage: https://github.com/Kal-Elx/paginated
repository: https://github.com/Kal-Elx/paginated
issue_tracker: https://github.com/Kal-Elx/paginated/issues
topics: [pagination, flutter, ui]

environment:
  sdk: ^3.8.1
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
